services:
  blogavel:
    image: blogavel:latest
    container_name: blogavel
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "80:80"
    environment:
      APP_KEY: <key>
      APP_TIMEZONE: UTC
      APP_URL: <url>

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: blogavel
      DB_USERNAME: admin
      DB_PASSWORD: <password>

      MINIO_KEY: blogavel
      MINIO_SECRET: <password>
      MINIO_BUCKET: blogavel
      MINIO_ENDPOINT: <public-endpoint>

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - custom_bridge_network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <password>
    volumes:
      - /app_data/docker_data/mysql:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - custom_bridge_network
    # ports:
    #   - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER: minioadmin
      - MINIO_ROOT_PASSWORD: <password>
    volumes:
      - /app_data/docker_data/minio:/data
    command: server --console-address ":9001" /data

networks:
  custom_bridge_network:
    name: custom_bridge_network
